# Generated by Django 4.1.7 on 2023-03-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_room_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient'),
        ),
    ]
