# Generated by Django 4.1.7 on 2023-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_room_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='prescription',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
