# Generated by Django 4.1.7 on 2023-03-02 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_admit_doctor_appointment_test_test_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admit',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='admit',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='doctor_appointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='doctor_appointment',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='transanction_id',
        ),
        migrations.RemoveField(
            model_name='test_appointment',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='test_appointment',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='admit',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient'),
        ),
        migrations.AddField(
            model_name='admit',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room'),
        ),
        migrations.AddField(
            model_name='doctor_appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor_appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient'),
        ),
        migrations.AddField(
            model_name='test',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient'),
        ),
        migrations.AddField(
            model_name='test',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transaction'),
        ),
        migrations.AddField(
            model_name='test_appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test_appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient'),
        ),
    ]
