# Generated by Django 4.1.7 on 2023-03-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_admit_patient_id_remove_admit_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admit',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admit',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room'),
        ),
    ]
