# Generated by Django 4.1.7 on 2023-03-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_admit_exit_time_alter_admit_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='test',
            name='patient',
        ),
    ]
