# Generated by Django 4.1.7 on 2023-03-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_test_doctor_remove_test_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
    ]
