# Generated by Django 4.1.7 on 2023-03-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_doctor_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_Appointment',
        ),
    ]
