# Generated by Django 4.1.7 on 2023-03-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_test_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='report_text',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
