# Generated by Django 4.1.7 on 2023-03-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_test_report_image_alter_test_report_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
    ]
